### ISSUE TITLE
Add Contributing file

### ISSUE THREAD

**Issue by Dun-sin** [Ba3a-G/Smart-Links#2]
Add the contributing file is useful for new contributors, so they know what to do in this project

Here's a reference link: [Contributing.md](https://mozillascience.github.io/working-open-workshop/contributing/)

**Comment by Ba3a-G** [comment]
Hey, thanks for pointing it out. Would you like to add it?

**Comment by Dun-sin** [comment]
What should be in the file is actually up to you, for example the rules people must follow to be able to contribute to this project, since it's your project only you can decide that

**Comment by Ba3a-G** [comment]
Dunzo!
